### ISSUE TITLE
Using a different host:port than localhost:8080 for web-client does not work

### ISSUE THREAD

**Issue by jorgemoralespou** [wildfly-swarm/booker#3]
Hi,
I would like to be able to run the server using any hostname and/or port for keycloak authentication.
If I do run web-client with:
````
mvn wildfly-swarm:run -Djboss.http.port=8081
````

Keycloak authentication does not work

**Comment by bobmcwhirter** [comment]
Keycloak has to know valid redirect URLs and stuff. If you want to run web client on different port, login as admin/admin to KC and adjust relevant URLs for that realm/app. 

--

**Comment by jorgemoralespou** [comment]
But this is no good solution for a cloud environment, where services may run in a variety of hosts/service names and in a variety of ports. This needs to be automated somehow, with a environment variable or something that can be specified per every keycloak server instance.
This can be scripted, but I find this a hack.
I'll check with keycloak devs to see what possibilities we have here.

**Comment by bobmcwhirter** [comment]
I know Keycloak can accept wild cards but I don't know if they can be applied at the port level. 

--

**Comment by bbrowning** [comment]
I had to solve this issue as well as part of getting Booker working on OpenShift. My changes aren't merged here yet, but I have a fork and branch at https://github.com/bbrowning/booker/tree/openshift where things live until I get everything working.

**Comment by kenfinnigan** [comment]
Should be resolved
